# Generated by Django 4.0.4 on 2022-04-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes_images', '0002_meme_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Surname',
            new_name='surname',
        ),
    ]
