# Generated by Django 4.0.4 on 2022-04-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes_images', '0003_rename_name_author_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestMeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes_images.bestmeme')),
            ],
        ),
    ]
