# Generated by Django 4.0.4 on 2022-04-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes_images', '0004_bestmeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestmeme',
            name='best',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes_images.meme'),
        ),
    ]
