# Generated by Django 4.0.4 on 2022-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes_images', '0005_alter_bestmeme_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BestMeme',
        ),
    ]
